"""Add base tables

Revision ID: 711d3fba903b
Revises: 
Create Date: 2023-05-29 20:44:23.227038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "711d3fba903b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "route",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("hashed", sa.String(length=256), nullable=False),
        sa.Column("departure_at", sa.DateTime(), nullable=False),
        sa.Column("arrival_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_hashed_departure_at", "route", ["hashed", "departure_at"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_hashed_departure_at", table_name="route")
    op.drop_table("route")
    # ### end Alembic commands ###
